# Converting Force and Displacement Columns to Stress and Strain

In [131]:
import pandas as pd
import math
df = pd.read_csv("data.csv")
df

             Force  Displacement Design Direction  Displacement Rate
0         0.000064     -0.000149      A         X                0.1
1        -0.000355     -0.000122      A         X                0.1
2         0.004733     -0.000355      A         X                0.1
3        -0.001949     -0.000374      A         X                0.1
4         0.003855     -0.000237      A         X                0.1
...            ...           ...    ...       ...                ...
108737 -190.590100    -26.780952      F         Y                1.8
108738 -190.616900    -26.782848      F         Y                1.8
108739 -190.604340    -26.783546      F         Y                1.8
108740 -190.614870    -26.785297      F         Y                1.8
108741 -190.608400    -26.783356      F         Y                1.8

[108742 rows x 5 columns]

In [137]:
surface_area = (3.18 * 3.2)
iheight = 25.4

In [139]:
force = df.iloc[:, 0]
stroke = df.iloc[: ,1]
stress = force / (3.18 * 3.2) # surface area
strain = stroke / 25.4 # initial height
stress_strain_df = pd.DataFrame({'Stress': stress, 'Strain': strain})
stress_strain_df

           Stress    Strain
0        0.000006 -0.000006
1       -0.000035 -0.000005
2        0.000465 -0.000014
3       -0.000192 -0.000015
4        0.000379 -0.000009
...           ...       ...
108737 -18.729373 -1.054368
108738 -18.732007 -1.054443
108739 -18.730772 -1.054470
108740 -18.731807 -1.054539
108741 -18.731171 -1.054463

[108742 rows x 2 columns]

In [149]:
# Reset the index of the original dataframe (ndf)
ndf_reset = ndf.reset_index(drop=True)

# Reset the index of the stress_strain_df dataframe
stress_strain_df_reset = stress_strain_df.reset_index(drop=True)

# Concatenate the two dataframes
df2 = pd.concat([ndf_reset, stress_strain_df_reset], axis=1)

# Display the concatenated dataframe
df2

       Design Direction  Displacement Rate     Stress    Strain
0           A         X                0.1   0.000006 -0.000006
1           A         X                0.1  -0.000035 -0.000005
2           A         X                0.1   0.000465 -0.000014
3           A         X                0.1  -0.000192 -0.000015
4           A         X                0.1   0.000379 -0.000009
...       ...       ...                ...        ...       ...
108737      F         Y                1.8 -18.729373 -1.054368
108738      F         Y                1.8 -18.732007 -1.054443
108739      F         Y                1.8 -18.730772 -1.054470
108740      F         Y                1.8 -18.731807 -1.054539
108741      F         Y                1.8 -18.731171 -1.054463

[108742 rows x 5 columns]

In [151]:
df2['Stress'] = df2['Stress'].abs()
df2['Strain'] = df2['Strain'].abs()
df2

       Design Direction  Displacement Rate     Stress    Strain
0           A         X                0.1   0.000006  0.000006
1           A         X                0.1   0.000035  0.000005
2           A         X                0.1   0.000465  0.000014
3           A         X                0.1   0.000192  0.000015
4           A         X                0.1   0.000379  0.000009
...       ...       ...                ...        ...       ...
108737      F         Y                1.8  18.729373  1.054368
108738      F         Y                1.8  18.732007  1.054443
108739      F         Y                1.8  18.730772  1.054470
108740      F         Y                1.8  18.731807  1.054539
108741      F         Y                1.8  18.731171  1.054463

[108742 rows x 5 columns]

In [153]:
df2.to_csv('PreProcessedData.csv')